language: java
sudo: true
os: linux
jdk:
- openjdk8

install:
- sudo apt update
- sudo apt install build-essential maven ant rustc cargo clang llvm cmake wget

script:
- cd ant
- ant
- cd ../make
- make
- cd ../maven
- mvn install test
- cd ../rust
- cargo build
- wget http://releases.llvm.org/7.0.1/llvm-7.0.1.src.tar.xz
- unxz llvm-7.0.1.src.tar.xz
- tar -xvf llvm-7.0.1.src.tar
- rm llvm-7.0.1.src.tar
- cd llvm-7.0.1.src
- mkdir build
- cd build
- cmake ..
- make
