language: java
sudo: true
os: linux
jdk:
- openjdk8

install:
- sudo apt update
- sudo apt install build-essential maven ant rustc cargo golang

script:
- cd ant
- ant
- cd ../make
- make
- cd ../maven
- mvn install test
- cd ../rust
- cargo build
- cd ../go
- go build main.go
