language: java
sudo: true
os: linux
jdk:
- openjdk8

install:
- sudo apt update
- sudo apt install build-essential maven ant ivy rustc cargo

script:
- cd ant
- ant
- cd ../make
- make
- cd ../maven
- mvn
- cd ../rust
- cargo build
